### ISSUE TITLE
猫影视TV新版 v2.0.0

### ISSUE THREAD

**Issue by qfwc258** [catvod/CatVodTVSpider#1]
请问猫影视TV新版 v2.0.0哪里可以下载，或是否开放源代码？

**Comment by catvod** [comment]
暂未对外开放，暂时没有开放APP源代码计划

**Comment by catvod** [comment]
> 请问猫影视TV新版 v2.0.0哪里可以下载，或是否开放源代码？

暂未对外开放，暂时没有开放APP源代码计划

**Comment by jimmyyao** [comment]
没有2.0.0的话 这个spider jar没啥用啊 所以2.0.0是要等到什么时候放出下载？
