### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by hasoelee** [catvod/CatVodTVSpider#2]
希望远程加载可以加密，不然老有人偷jar包。

**Comment by catvod** [comment]
> 希望远程加载可以加密，不然老有人偷jar包。

额 (⊙o⊙)…

**Comment by wing0110210317** [comment]
希望大佬把影视工厂和追剧达人集成进去，谢谢了

**Comment by chunaj2** [comment]
希望大佬把9亿看看（www.9ehao.com）集成进去，谢谢了
