### ISSUE TITLE
希望能加上优质源 骚火 巴士

### ISSUE THREAD

**Issue by 3194819809** [catvod/CatVodTVSpider#26]
https://dm84.tv/  https://saohuotv.com/

**Comment by lite-cucumber** [comment]
> https://dm84.tv/ https://saohuotv.com/

等会我就满足你

**Comment by 3194819809** [comment]
> 
> 
> > [https://dm84.tv/ ](https://dm84.tv/) [https://saohuotv.com/ ](https://saohuotv.com/)
> 
> 等会我就满足你
谢谢

**Comment by pglblb** [comment]
> 
> 
> > https://dm84.tv/ https://saohuotv.com/
> 
> 等会我就满足你

大佬 ，可否百忙之中抽时间帮一下忙
把蛋蛋赞影院（https://www.dandanzan.cc/）、多电影网（https://dd520.cc/）、影院集合（https://www.ysjihe.cc/）、电影牛（https://www.dianyingn.cc/）、低端影视（https://ddrk.me/）、悟空美剧（https://www.wukongmeiju.com/）做成xpath或简单搜索页，感谢。
