### ISSUE TITLE
使用 gitee上的接口文件

### ISSUE THREAD

**Issue by CCSH** [catvod/CatVodTVSpider#42]
使用 gitee上的接口文件的原始数据，能访问数据源名字 但是内容没有，我记得之前可以用gitee做接口配置的

**Comment by yoyodadada** [comment]
> 使用 gitee上的接口文件的原始数据，能访问数据源名字 但是内容没有，我记得之前可以用gitee做接口配置的

作者已经屏蔽了gitee的域名做为接口，配置接口不能放在gitee上，否则只能列出列表，无法获取内容。

**Comment by CCSH** [comment]
> > 使用 gitee上的接口文件的原始数据，能访问数据源名字 但是内容没有，我记得之前可以用gitee做接口配置的
> 
> 作者已经屏蔽了gitee的域名做为接口，配置接口不能放在gitee上，否则只能列出列表，无法获取内容。

不只是gitee 仓库托管的都不可以

**Comment by heyuhua1992** [comment]
可以使用gitee的接口文件，就是不能用gitee pages的方式

比如：
https://heyuhua.gitee.io/tv/list.json
不行

而
https://gitee.com/heyuhua/tv/raw/master/list.json
可以

详细可以看看
#94
