### ISSUE TITLE
建议主页面小窗播放界面下增加一键快速直达（转换）当前片名到快速搜索页面功能

### ISSUE THREAD

**Issue by pglblb** [catvod/CatVodTVSpider#45]
主页面小窗播放页面，建议增加一键搜索当前播放片名快速转换到搜索页面直接搜索，而不需要在搜索页面再扫码另行输入影片名，达到快捷方便使用目的，这个功能非常体贴有用。

**Comment by lite-cucumber** [comment]
我帮你转达给猫猫大人了
