### ISSUE TITLE
反馈问题

### ISSUE THREAD

**Issue by 250662772** [catvod/CatVodTVSpider#47]
xpath套娃规则如果碰到网站线路名称一样的只会显示一条线路，还有如果线路名称前面有换行也会不显示

**Comment by lite-cucumber** [comment]
自己从规则上想办法处理。

**Comment by 250662772** [comment]
> 自己从规则上想办法处理。

不修改java,只修改规则是没用的，猫遇见线路名称一样的只显示一条，比如有3条线路名称都是云播，猫里面只能显示一条云播，另外2条估计当重复的过滤了

**Comment by lite-cucumber** [comment]
> > 自己从规则上想办法处理。
> 
> 不修改java,只修改规则是没用的，猫遇见线路名称一样的只显示一条，比如有3条线路名称都是云播，猫里面只能显示一条云播，另外2条估计当重复的过滤了

改规则把一样的处理成不一样不就行了，怎么没用

**Comment by lite-cucumber** [comment]
> > > 自己从规则上想办法处理。
> > 
> > 
> > 不修改java,只修改规则是没用的，猫遇见线路名称一样的只显示一条，比如有3条线路名称都是云播，猫里面只能显示一条云播，另外2条估计当重复的过滤了
> 
> 改规则把一样的处理成不一样不就行了，怎么没用

搞不定就上规则。

**Comment by 250662772** [comment]
关了吧，等你自己遇到问题再修复吧

**Comment by lite-cucumber** [comment]
> 关了吧，等你自己遇到问题再修复吧

你说的问题是一定可以通过规则解决的，线路一样规则里处理成不一样就完事了
