### ISSUE TITLE
农民影视https://v.emsdn.cn/在猫里面电视剧基本都解析不出来，电影可以正常解析播放

### ISSUE THREAD

**Issue by xi008** [catvod/CatVodTVSpider#65]
猫神看看是什么问题？网页里面播放电视剧都正常，唯独电视剧大部分在猫里面解析失败，电影解析正常秒播

**Comment by Tangsan99999** [comment]
配置里也没农民影视，怎么知道问题在哪，用猜么？😂

**Comment by 250662772** [comment]
> 配置里也没农民影视，怎么知道问题在哪，用猜么？😂

用的xpath规则，电视剧星辰大海在浏览器里面嗅探出的地址http://v3-default.ixigua.com/13f8410cf5f5c3a0f231622e69b0b0d8/619aed11/video/tos/cn/tos-cn-ve-192/e49b1b056e864481a1d3b494d5d0865c/?a=2011&br=871&bt=871&cd=0%7C0%7C0&ch=0&cr=0&cs=0&dr=0&ds=3&er=&ft=teqIn88-os2DpTTh7TQ_plXxuhsdz5toHqY&l=20211122072155010210067148134FE412&lr=&mime_type=video_mp4&net=0&pl=0&qs=0&rc=M3BtdTc6ZnY5OTMzNDMzM0ApPDdmaThnNGU6N2Q3NzZnN2cvZ2dxcjRfb2FgLS1kYGFzczA1YS4zLjQuYy4yMTE0YC06Yw%3D%3D&vl=&vr=
这种播放地址猫是不是不识别？

**Comment by lite-cucumber** [comment]
给播放页地址

**Comment by xi008** [comment]
> 给播放页地址

https://v.emsdn.cn/vod-play-id-39111-src-1-num-40.html

**Comment by lite-cucumber** [comment]
已修复，更新jar
