### ISSUE TITLE
duboku.tv视频无法解析

### ISSUE THREAD

**Issue by FishingcatYu** [catvod/CatVodTVSpider#79]
我按duboku.json修改了一个json
`{
  "ua": "",
  "homeUrl": "https://www.duboku.tv",
  "dcVipFlag": "true",
  "pCfgJs": "https://tv.gboku.com/static/js/playerconfig.js",
  "pCfgJsR": "[\\W|\\S|.]*?MacPlayerConfig.player_list[\\W|\\S|.]*?=([\\W|\\S|.]*?),MacPlayerConfig.downer_list",
  "dcShow2Vip": {},
  "dcPlayUrl": "true",
  "cateNode": "//ul[contains(@class,'myui-header__menu nav-menu')]/li[contains(@class, 'dropdown-hover')]//div/ul/li/a[contains(@href, 'vodtype') and not(contains(@href,'label'))]",
  "cateName": "/text()",
  "cateId": "/@href",
  "cateIdR": "/vodtype/(\\w+).html",
  "cateManual": {},
  "homeVodNode": "//div[contains(@class, 'padding-0')]//ul[contains(@class,'myui-vodlist')]/li//a[contains(@class,'myui-vodlist__thumb')]",
  "homeVodName": "/@title",
  "homeVodId": "/@href",
  "homeVodIdR": "/voddetail/(\\w+).html",
  "homeVodImg": "/@data-original",
  "homeVodImgR": "\\S+(http\\S+)",
  "homeVodMark": "/span[contains(@class,'pic-text')]/text()",
  "cateUrl": "https://tv.gboku.com/vodtype/{cateId}-{catePg}.html",
  "cateVodNode": "//ul[contains(@class,'myui-vodlist')]//li//a[contains(@class,'myui-vodlist__thumb')]",
  "cateVodName": "/@title",
  "cateVodId": "/@href",
  "cateVodIdR": "/voddetail/(\\w+).html",
  "cateVodImg": "/@data-original",
  "cateVodImgR": "\\S+(http\\S+)",
  "cateVodMark": "/span[contains(@class,'pic-text')]/text()",
  "dtUrl": "https://tv.gboku.com/voddetail/{vid}.html",
  "dtNode": "//div[contains(@class,'col-lg-wide-75')]",
  "dtName": "//div[@class='myui-content__thumb']/a[contains(@class,'myui-vodlist__thumb')]/@title",
  "dtNameR": "",
  "dtImg": "//div[@class='myui-content__thumb']/a[contains(@class,'myui-vodlist__thumb')]/img/@data-original",
  "dtImgR": "\\S+(http\\S+)",
  "dtCate": "//div[@class='myui-content__detail']//span[contains(@class,'text-muted') and contains(text(), '分类')]/following-sibling::*/text()",
  "dtCateR": "",
  "dtYear": "//div[@class='myui-content__detail']//span[contains(@class,'text-muted') and contains(text(), '年份')]/following-sibling::*/text()",
  "dtYearR": "",
  "dtArea": "//div[@class='myui-content__detail']//span[contains(@class,'text-muted') and contains(text(), '地区')]/following-sibling::*/text()",
  "dtAreaR": "",
  "dtMark": "//div[@class='myui-content__detail']//span[contains(@class,'text-muted') and contains(text(), '更新')]/following-sibling::*/text()",
  "dtMarkR": "",
  "dtActor": "//div[@class='myui-content__detail']//span[contains(@class,'text-muted') and contains(text(), '主演')]/following-sibling::*/text()",
  "dtActorR": "",
  "dtDirector": "//div[@class='myui-content__detail']//span[contains(@class,'text-muted') and contains(text(), '导演')]/following-sibling::*/text()",
  "dtDirectorR": "",
  "dtDesc": "//div[@class='myui-content__detail']//span[contains(@class,'text-muted') and contains(text(), '简介')]/parent::text()",
  "dtDescR": "",
  "dtFromNode": "//a[@data-toggle='tab' and contains(@href, 'playlist')]",
  "dtFromName": "/text()",
  "dtFromNameR": "",
  "dtUrlNode": "//div[contains(@class,'tab-content')]/div[contains(@id, 'playlist')]",
  "dtUrlSubNode": "//li/a",
  "dtUrlId": "@href",
  "dtUrlIdR": "/vodplay/(\\S+).html",
  "dtUrlName": "/text()",
  "dtUrlNameR": "",
  "playUrl": "https://tv.gboku.com/vodplay/{playUrl}.html",
  "playUa": "",
  "searchUrl": "https://tv.gboku.com/index.php/ajax/suggest?mid=1&wd={wd}&limit=10",
  "scVodNode": "json:list",
  "scVodName": "name",
  "scVodId": "id",
  "scVodIdR": "",
  "scVodImg": "pic",
  "scVodMark": ""
}`
并增加了一个在线解析“https://okjx.cc/?url=“
app中可以获取网站分类、剧集，但是视频无法解析
电脑端测试在线解析地址是可以播放网站的视频的，例如
在电脑端https://tv.gboku.com/vodplay/2468-1-1.html中视频地址https://t.wdubo.com/20211201/hrW52zAE/hls/index.m3u8用https://okjx.cc/?url=https://t.wdubo.com/20211201/hrW52zAE/hls/index.m3u8可以正常播放，但app中视频无法解析，请指教。

**Comment by Tangsan99999** [comment]
更换系统播放器或exo播放器试试

**Comment by FishingcatYu** [comment]
> 更换系统播放器或exo播放器试试

试过，无法解析。我刚刚试了你的cat里的my.json，我看里面也有这个网站，但也是解析不了，你自己的可以用么？

**Comment by Tangsan99999** [comment]
独播库好像不用解析吧，xpath就好。

**Comment by FishingcatYu** [comment]
> 独播库好像不用解析吧，xpath就好。

是用的xpath，app中电视剧选集，如果是catcod库用自己修改的json，转圈 “解析播放地址”，然后三角形中感叹号，“解析播放地址失败”，所以我以为是使用json里的解析；如果用你的my.json，就是没有文字提示，就是转圈，然后三角形中感叹号。

**Comment by Tangsan99999** [comment]
我一切正常，没缘分，用别的吧
