### ISSUE TITLE
app问题在哪反馈，有一个关于播放的问题

### ISSUE THREAD

**Issue by smallmagpie** [catvod/CatVodTVSpider#82]
播放高清直播源的时候，经常出现画面卡住的问题，如果不重新刷新一下就会一直卡住，这个应该怎么解决

**Comment by pglblb** [comment]
电视直播源解码有问题，这个直播就是个基本功能，就当玩玩，要看直播还是下专业的直播软件吧。

**Comment by smallmagpie** [comment]
> 电视直播源解码有问题，这个直播就是个基本功能，就当玩玩，要看直播还是下专业的直播软件吧。

哎，找了些其他直播的，主要是都有广告、购物台之类，直播源我能找到，就是没有类似完全自定义的软件，希望能够搞好这个软件直播功能，这样就不用看个电视到处换软件看

**Comment by pglblb** [comment]
可以用星火直播海外版



***@***.***
 
发件人： smallmagpie
发送时间： 2021-12-24 22:54
收件人： catvod/CatVodTVSpider
抄送： pglblb; Comment
主题： Re: [catvod/CatVodTVSpider] app问题在哪反馈，有一个关于播放的问题 (Issue #82)
电视直播源解码有问题，这个直播就是个基本功能，就当玩玩，要看直播还是下专业的直播软件吧。
哎，找了些其他直播的，主要是都有广告、购物台之类，直播源我能找到，就是没有类似完全自定义的软件，希望能够搞好这个软件直播功能，这样就不用看个电视到处换软件看
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
