### ISSUE TITLE
猫影视TV优化方向。。。

### ISSUE THREAD

**Issue by fj365** [catvod/CatVodTVSpider#84]
猫影视TV是否更新了2.0.7版本?
还是某些不坏好意的人破解更新的版本。
直播源连接设置超时自动切换源。
直播源是否支持P2-9P/mitv/vjms/sop/tvbus等等格式。
播放器是否支持调用外部播放器（mx/pot/x/o/nplayer）。
接口文件是否支持官方唯一编解码加解密。
点播-直播差个音乐版块完美(再加个在线聊天室更完美)。
爬宠希望采用lua语言更方便实用。

**Comment by catvod** [comment]
207群内测试 
lua 需要可以自己想办法封装 
别的没有
