### ISSUE TITLE
麻烦大佬发个群链接

### ISSUE THREAD

**Issue by xingleiwu** [catvod/CatVodTVSpider#86]
万分感谢

**Comment by william7651** [comment]
目前地址都是固定了，不可以使用自己的链接源。好处是大家不用找点播源都基本上很全面，坏处就是直播源都是固定的也不全面，而有些个人爱好想看看港澳台的又没有！能否单独打开一个自定义接口可以让爱好者自己添加直播源呢？

**Comment by xingleiwu** [comment]
麻烦大佬  支持
CatVodTV  能不能拉我进群 谢谢  @wuyongshusheng

**Comment by pglblb** [comment]
743073078猫影视爱好者内部交流群
