### ISSUE TITLE
app不支持MP2编码音频的视频，无声音

### ISSUE THREAD

**Issue by tanxianbo** [catvod/CatVodTVSpider#97]
app不支持MP2编码音频的视频，无声音，下面链接是MP2编码音频（只能广东电信访问）

rtsp://183.59.156.50/PLTV/88888905/224/3221229811/10000100000000060000000009467087_0.smil?accountinfo=%7E%7EV2.0%7EQRLIDngmxvSnsGioni22UA%7Ed8zaBpb8sc8waRHlcygGKa7DGzQQ9i7duhAHQFCZPUBjq0LKoV4na6KugffIjt5gaIF1Y1UboynP2zzOHjUBaMiexQMKedrWXSl4uo9ReG8%7EExtInfoWNHSPSTb%2B3AG0FnUkYLPMw%3D%3D%3A20220202025952%2C23440698%2C218.19.244.237%2C20220202025952%2C02000006000000052018092799000001%2C23440698%2C-1%2C0%2C1%2C%2C%2C2%2C%2C%2C%2C2%2C%2CEND&GuardEncType=2

**Comment by catvod** [comment]
给测试地址。

**Comment by tanxianbo** [comment]
上面的rtsp就是测试地址，长期有效（限广东电信访问）
ijkplayer-android/config配置文件加入如下编译参数即可，本人已编译和测试
`export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-encoder=mp2"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mp2"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-muxer=mp2"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mp2float"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-encoder=mp2fixed"`

**Comment by tanxianbo** [comment]
广东广州这边一手iptv源都是rtsp协议，希望大佬下次更新支持下
